### ISSUE TITLE
请问，本教程参考的源教程是？

### ISSUE THREAD

**Issue by FankLi** [uncleguanghui/pyflink_learn#1]
首先，感谢你的教程，很好的让一个python 选手入门flink.
您的教程是源自哪里呢？谢谢

**Comment by uncleguanghui** [comment]
> 首先，感谢你的教程，很好的让一个python 选手入门flink.
> 您的教程是源自哪里呢？谢谢

我写的这个教程，基本上都是源自于我通读官方文档后做的总结，边学、边实践、边总结，才能理解得更深刻。

Flink 还在快速发展中，每个新版本都会出现很多特性，并且可能没有向后兼容，因此网上很多中文教程可能都已经部分过时了。所以，我还是建议通读官方文档，相信你也会有新的收获。

**Comment by FankLi** [comment]
好的了解，感谢
