### ISSUE TITLE
第五个例子如何体现反馈？

### ISSUE THREAD

**Issue by yinghaodang** [uncleguanghui/pyflink_learn#25]
你好，我的理解中，在线机器学习并不仅仅是将模型搬运到Redis里。
而是模型会随着我的反馈有所变化。
我觉得你给的例子已经将这个框架基本搞定了，唯独少了如何去做反馈。
在前端页面中，只有输入输出清除三个交互点。
我认为得加一个框框让用户自己输入正确的答案，然后这个结果反馈到flink中，重新调整参数的值。

**Comment by uncleguanghui** [comment]
哈哈哈是的，只是我偷懒了，原来还是有人会看得仔细



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yinghaodang ***@***.***&gt;
发送时间: 2023年5月26日 15:13
收件人: uncleguanghui/pyflink_learn ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [uncleguanghui/pyflink_learn] 第五个例子如何体现反馈？ (Issue #25)





 
你好，我的理解中，在线机器学习并不仅仅是将模型搬运到Redis里。
 而是模型会随着我的反馈有所变化。
 我觉得你给的例子已经将这个框架基本搞定了，唯独少了如何去做反馈。
 在前端页面中，只有输入输出清除三个交互点。
 我认为得加一个框框让用户自己输入正确的答案，然后这个结果反馈到flink中，重新调整参数的值。
