### ISSUE TITLE
flink web ui metrics 没有显示评估效果

### ISSUE THREAD

**Issue by 7125messi** [uncleguanghui/pyflink_learn#5]
大佬，我用的是flink 1.11.2，多次手写数字在线学习完  查看metrics  没有显示任务结果，是版本的问题的吗？需要升级到 1.12吗？

**Comment by uncleguanghui** [comment]
添加了指标了吗？Add Metric

**Comment by 7125messi** [comment]
发现model代码里看不到 open 的调用?

**Comment by uncleguanghui** [comment]
这是 UDF 默认的写法，定义就行了
