### ISSUE TITLE
哪里执行了eval 方法

### ISSUE THREAD

**Issue by FankLi** [uncleguanghui/pyflink_learn#7]
案例5_online_machine_learning中，代码在哪一行执行了模型训练的方法eval ？

一直没看明白，期待你的回复

**Comment by uncleguanghui** [comment]
eval 方法不需要显式地调用，只要定义了就行，并且保证 eval 传入的参数及其类型与 sql 里的一一对应即可。

Flink 会在流处理时自动运行 eval 方法的，详见官方文档：https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/table/functions/udfs.html#evaluation-methods

**Comment by FankLi** [comment]
嗯呢，不好意思，刚入门，问了一个弱智问题

可否添加一下WX，方便想你请教，谢谢

**Comment by uncleguanghui** [comment]
不好意思，还是邮件沟通吧，欢迎随时聊天~
