### ISSUE TITLE
请问目前pyflink支持调用jar包里自定义的processWindowFunction吗

### ISSUE THREAD

**Issue by MaleicAcid** [uncleguanghui/pyflink_learn#8]
特别感谢您的教程，对我帮助非常大！我看了第四章的教程发现是调用了jar包里的aggregateFunction来实现的TopN, 但我的功能需要对一个滚动窗口使用全量聚合processWindowFunction, 输出也会是多行或者0行。
想请教一下这种情况应该怎么写呢, 还是在tableAPI里用select吗， 我查了官方文档实在是没找到这种示例 😳

**Comment by uncleguanghui** [comment]
我好像也没有看到 pyflink + processWindowFunction 的相关资料。

听上去，你的需求好像也可以用 aggregateFunction 来实现，本质上是一样的。
